### PR TITLE
Improve (partially fix) upload.af and uploadX resolvers

### PR DESCRIPTION
**Pull request by thomas-ernest**
Upload.af and UploadX are not working for few months. This pull request aims at going further in Upload.af and UploadX download flow resolution.

Though this fix, Upload.af and UploadX download flow resolution are still blocked at Google ReCaptcha.

Similar changes were made for ClicknUpload host and likewise there is a dependency on Kodi Krypton (because of https:// and Python 2.7.9 dependency. urllib2 and ssl SNI support or so).

Finally, there is a formatting of resolvers.py, which makes the review painful without the ignore withespace option.

### CODE REVIEW

**Comment by thomas-ernest** [comment]
- [ ] Next step is to allow user to pass Google ReCaptcha. Maybe by opening the url with the captcha in a webdriver to allow the user to click an potentially be verified.

Something with 2Captcha was done in [VVLID's repo](https://github.com/VVILD/recaptchabreaker). A webdriver for Chrome was done in [Andrew Leech's repo](https://github.com/andrewleech/script.module.webdriver).

**Comment by Eldorados** [comment]
These hosts have been fixed quite some time ago in urlresolver which Icefilms now uses, the resolver.py is no longer usedThey are dependent on new python and are working well with it                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Thomas ERNESTSent: Friday, December 30, 2016 7:45 PMTo: Eldorados/icefilms-addonReply To: Eldorados/icefilms-addonCc: SubscribedSubject: [Eldorados/icefilms-addon] Bugfix/Improve upload.af and uploadX resolvers (#5)Upload.af and UploadX are not working for few months. This pull request aims at going further in Upload.af and UploadX download flow resolution.
Though this fix, Upload.af and UploadX download flow resolution are still blocked at Google ReCaptcha.
Similar changes were made for ClicknUpload host and likewise there is a dependency on Kodi Krypton (because of https:// and Python 2.7.9 dependency. urllib2 and ssl SNI support or so).
Finally, there is a formatting of resolvers.py, which makes the review painful without the ignore withespace option.



You can view, comment on, or merge this pull request online at:
  https://github.com/Eldorados/icefilms-addon/pull/5

Commit Summary

  Fix resolvers for upload.af and uploadx (up to captcha)
  Merge branch 'master' into bugfix/uploadaf_and_uploadx_resolvers
  Bump version
  Add documentation of get_hidden


File Changes

  
    M
    addons.xml
    (2)
  
  
    M
    plugin.video.icefilms/changelog.txt
    (5)
  
  
    M
    plugin.video.icefilms/resources/lib/resolvers.py
    (686)
  


Patch Links:

  https://github.com/Eldorados/icefilms-addon/pull/5.patch
  https://github.com/Eldorados/icefilms-addon/pull/5.diff


—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Eldorados/icefilms-addon","title":"Eldorados/icefilms-addon","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Eldorados/icefilms-addon"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Bugfix/Improve upload.af and uploadX resolvers (#5)"}],"action":{"name":"View Pull Request","url":"https://github.com/Eldorados/icefilms-addon/pull/5"}}}

**Comment by thomas-ernest** [comment]
Thank you for the info. For the details it seems to be related to commit https://github.com/Eldorados/script.module.urlresolver/commit/861853963a00756d16caf6fd6da036d98d95165d

Do you think it is worth provide a PR to icefilms-addon repo updating the dependencies of urlresolver 3.0.22 and to Kody 17.0 (for Python) ? And a pair of PR to move ClicknUpload resolver from icefilms-addon to URLResolver ?

**Comment by Eldorados** [comment]
Hey, no there's not a need to update the references, it will always utilize
the latest version of urlresolver unless they have turned off
auto-updates... otherwise Icefilms will fail when they try updating with a
dependencies not met, I don't want to cause those types of issues

Also making Icefilms dependent on Kodi 17 (which isn't released yet) isn't
good either as this https issue is only on Windows and I believe Android..
so we would be forcing other uses to upgrade when they don't need/want to

There is something else I believe we should do which is in URLResolver,
detect the https error and display a msg telling the user how to fix ie.
upgrade Kodi

**Pull request closed without merging**
